# use the official nodejs LTS image
FROM node:18-alpine

#set the working directory
WORKDIR /app

# copy package.json and package-lock.json (if available)
COPY package*.json ./

# install dependencies
RUN npm install

# copy the rest of the applicatiion files
COPY . .

#Expose port 3003
EXPOSE 3003

# Start the application
CMD ["node", "server.js"]